import os


BUCKET_NAME = 'lunchtag-slack-bot-user-data'
ADDITIONAL_USERS = ['U03UFPNSDT6', 'U03UFPNSDT6', 'U03UFPNSDT6']
AVOID_ADJUSTMENT_WEIGHT = 1000
PROMOTE_ADJUSTMENT_WEIGHT = 10
HISTORY_PENALTY = 100
SELF_MATCH_PENALTY = 10000

specific_users = ["U03UFPNSDT6", "U03UD78Q7MZ"]
admin_users = ["U03UFPNSDT6", "U03UD78Q7MZ"]

SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN')

messages = {'invite': "Would you like to join the LunchTag program?",
            
            'weekly_interest': "Hey! Please confirm your availability for LunchTag this week.",
            
            'weekly_interest_followup': 'Hey! We are sending out pairings soon, please respond to the last message to update your status!',
            
            'missing_user': "Sorry, I couldn't find your profile in our database.",
            
            'get_user_profile': '{real_name}, here is your user profile:\n'
                '     • Status: {status}\n'
                '     • This Weeks Interest: {weekly_interest}\n'
                '     • Interests: {Interests}\n'
                '     • Custom Interest: {Custom_Interest}\n'
                '     • Promoted People: {Promoted_People}\n'
                '     • Avoided People: {Avoid_People}\n'
                '     • LunchTag History: {History}\n'
                '     • Survey History: {Survey}',
            
            'admin_controls': 'Here are available admin commands:\n'
                '\nAdmin Views:\n'
                '     • /lunchtag-admin view -> Sends full user data\n'
                '\nUser controls:\n'
                '     • /lunchtag-admin invite {all, specified_users}  -> will invite all users, or provided users to Lunchtag\n'
                '     • /lunchtag-admin confirm -> clears last status and messages LunchTag users to ask for their status\n'
                '     • /lunchtag-admin confirm-followup -> reminds non-responders to respond to confirm message\n'
                '\nPairings Management:\n'

                '     • /lunchtag-admin pairings {tiny, short, full} -> provides sized response file of existing pairings\n'
                '     • /lunchtag-admin generate {tiny, short, full} -> generates new pairings and provides sized response file\n'
                '     • /lunchtag-admin swap [A1, B2] -> Swaps two users in the pairings\n'
                '     • /lunchtag-admin publish -> publishes pairings by DMing everyone\n'

}



true = True
all_blocks =    {'invite': 
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": "Join LunchTag", "emoji": true } }, { "type": "image", "image_url": "https://avatars.slack-edge.com/2023-04-03/5038467273319_68c21914f81135204822_512.png", "alt_text": "inspiration" }, { "type": "section", "text": { "type": "mrkdwn", "text": ":thinking_face: *What is Lunchtag?*" } }, { "type": "section", "text": { "type": "mrkdwn", "text": "Lunchtag is a casual program where we will pair you with another UT EA member each week to get together for lunch (or dinner, or a walk, or whatever works best)! This is a chance for you to learn more about each other, mutually support and provide feedback on career/life plans, discuss EA ideas, and/or talk about anything else of interest!" } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": ":tada: Join LunchTag :tada:" }, "style": "primary", "value": "invite_accepted" }, { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": "Decline" }, "style": "danger", "value": "invite_declined" } ] } ] },
                'invite_accepted':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": "Join LunchTag", "emoji": true } }, { "type": "image", "image_url": "https://avatars.slack-edge.com/2023-04-03/5038467273319_68c21914f81135204822_512.png", "alt_text": "inspiration" }, { "type": "section", "text": { "type": "mrkdwn", "text": ":thinking_face: *What is Lunchtag?*" } }, { "type": "section", "text": { "type": "mrkdwn", "text": "Lunchtag is a casual program where we will pair you with another UT EA member each week to get together for lunch (or dinner, or a walk, or whatever works best)! This is a chance for you to learn more about each other, mutually support and provide feedback on career/life plans, discuss EA ideas, and/or talk about anything else of interest!" } }, { "type": "section", "text": { "type": "mrkdwn", "text": ">:white_check_mark: *Thanks for joining!* Complete your profile to get included in the next pairings." } } ] },
                'invite_declined':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": "Join LunchTag", "emoji": true } }, { "type": "image", "image_url": "https://avatars.slack-edge.com/2023-04-03/5038467273319_68c21914f81135204822_512.png", "alt_text": "inspiration" }, { "type": "section", "text": { "type": "mrkdwn", "text": ":thinking_face: *What is Lunchtag?*" } }, { "type": "section", "text": { "type": "mrkdwn", "text": "Lunchtag is a casual program where we will pair you with another UT EA member each week to get together for lunch (or dinner, or a walk, or whatever works best)! This is a chance for you to learn more about each other, mutually support and provide feedback on career/life plans, discuss EA ideas, and/or talk about anything else of interest!" } }, { "type": "section", "text": { "type": "mrkdwn", "text": ">:no_entry:  *You declined to join!* Reconsider anytime with /Lunchtag-join" } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "text": "Reconsider", "emoji": true }, "value": "invite_reconsider", "style": "primary" } ] } ] },
                
                'weekly_interest':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": "Confirm for next Lunchtag Round", "emoji": true } }, { "type": "section", "text": { "type": "plain_text", "text": "Hey! Are you ready for the next round of LunchTag? You can also skip this week, or pause your lunchtag subscription for a period.", "emoji": true } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": ":white_check_mark: Ready for next pairing" }, "style": "primary", "value": "weekly_interest_confirmed" }, { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": ":mailbox: Skip this week" }, "value": "weekly_interest_skipping" }, { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": ":double_vertical_bar: Pause" }, "value": "weekly_interest_paused" } ] } ] },
                'weekly_interest_confirmed':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": "Confirm for next Lunchtag Round", "emoji": true } }, { "type": "section", "text": { "type": "plain_text", "text": "Hey! Are you ready for the next round of LunchTag? You can also skip this week, or pause your lunchtag subscription for a period.", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": ">:white_check_mark:  *You're confirmed!* Expect a pairing in the next few days :grin:" } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "text": "Change my status", "emoji": true }, "value": "weekly_interest_reconsider" } ] } ] },
                'weekly_interest_skipping':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": "Confirm for next Lunchtag Round", "emoji": true } }, { "type": "section", "text": { "type": "plain_text", "text": "Hey! Are you ready for the next round of LunchTag? You can also skip this week, or pause your lunchtag subscription for a period.", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": ">:mailbox:  *You're skipping this week.* We hope to see you back soon!" } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "text": "Change my status", "emoji": true }, "value": "weekly_interest_reconsider" } ] } ] },
                'weekly_interest_paused':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": "Confirm for next Lunchtag Round", "emoji": true } }, { "type": "section", "text": { "type": "plain_text", "text": "Hey! Are you ready for the next round of LunchTag? You can also skip this week, or pause your lunchtag subscription for a period.", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": ">:double_vertical_bar:  *You're Lunchtag subscription is paused.* We hope to see you back soon!" } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "text": "Change my status", "emoji": true }, "value": "weekly_interest_reconsider" } ] } ] },
                
                'profile':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":basket: Your Lunchtag Profile :takeout_box:", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": "Our system will use your profile & interests to pair you with others, select things you'd enjoy discussing!" } }, { "type": "input", "block_id": "all_interests", "element": { "type": "checkboxes", "options": [ { "text": { "type": "plain_text", "text": ":trackball: AI Risk", "emoji": true }, "value": "AI Risk" }, { "text": { "type": "plain_text", "text": ":chicken: Animal Welfare", "emoji": true }, "value": "Animal Welfare" }, { "text": { "type": "plain_text", "text": ":earth_africa: Global Health", "emoji": true }, "value": "Global Health" }, { "text": { "type": "plain_text", "text": ":syringe: Biorisk", "emoji": true }, "value": "Biorisk" }, { "text": { "type": "plain_text", "text": ":person_in_lotus_position: Mental Health", "emoji": true }, "value": "Mental Health" } ], "action_id": "checkboxes-action" }, "label": { "type": "plain_text", "text": "Interests", "emoji": true } }, { "type": "input", "block_id": "custom_interest", "element": { "type": "plain_text_input", "action_id": "plain_text_input-action" }, "label": { "type": "plain_text", "text": "[Optional] Any other interests you want to share?", "emoji": true } }, { "type": "divider" }, { "type": "input", "block_id": "promoted_people", "element": { "type": "multi_users_select", "placeholder": { "type": "plain_text", "text": "Select users", "emoji": true }, "action_id": "multi_users_select-action" }, "label": { "type": "plain_text", "text": "[Optional] Is there anyone in particular you'd like to be paired with?", "emoji": true } }, { "type": "input", "block_id": "avoid_people", "element": { "type": "multi_users_select", "placeholder": { "type": "plain_text", "text": "Select users", "emoji": true }, "action_id": "multi_users_select-action" }, "label": { "type": "plain_text", "text": "[Optional] Is there anyone in particular you'd like *not* to be paired with?", "emoji": true } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": "Create profile" }, "style": "primary", "value": "profile_update" } ] } ] },
                    
                'profile_update':
                    { "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":basket: Your Lunchtag Profile :takeout_box:", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": "Our system will use your profile & interests to pair you with others, select things you'd enjoy discussing!" } }, { "type": "input", "block_id": "all_interests", "element": { "type": "checkboxes", "options": [ { "text": { "type": "plain_text", "text": ":trackball: AI Risk", "emoji": true }, "value": "AI Risk" }, { "text": { "type": "plain_text", "text": ":chicken: Animal Welfare", "emoji": true }, "value": "Animal Welfare" }, { "text": { "type": "plain_text", "text": ":earth_africa: Global Health", "emoji": true }, "value": "Global Health" }, { "text": { "type": "plain_text", "text": ":syringe: Biorisk", "emoji": true }, "value": "Biorisk" }, { "text": { "type": "plain_text", "text": ":person_in_lotus_position: Mental Health", "emoji": true }, "value": "Mental Health" } ], "action_id": "checkboxes-action" }, "label": { "type": "plain_text", "text": "Interests", "emoji": true } }, { "type": "input", "block_id": "custom_interest", "element": { "type": "plain_text_input", "action_id": "plain_text_input-action" }, "label": { "type": "plain_text", "text": "[Optional] Any other interests you want to share?", "emoji": true } }, { "type": "divider" }, { "type": "input", "block_id": "promoted_people", "element": { "type": "multi_users_select", "placeholder": { "type": "plain_text", "text": "Select users", "emoji": true }, "action_id": "multi_users_select-action" }, "label": { "type": "plain_text", "text": "[Optional] Is there anyone in particular you'd like to be paired with?", "emoji": true } }, { "type": "input", "block_id": "avoid_people", "element": { "type": "multi_users_select", "placeholder": { "type": "plain_text", "text": "Select users", "emoji": true }, "action_id": "multi_users_select-action" }, "label": { "type": "plain_text", "text": "[Optional] Is there anyone in particular you'd like *not* to be paired with?", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": ">:white_check_mark: Your profile has been set. Update it anytime" } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": "Update profile" }, "value": "profile_update" } ] } ] },
                
                'survey':
                    { "blocks": [ { "type": "section", "text": { "type": "mrkdwn", "text": "Before the next Lunchtag pairings, please complete the survey below! We'll use it to try to improve your experience." } }, { "type": "input", "block_id": "MetUp", "element": { "type": "static_select", "placeholder": { "type": "plain_text", "text": "Select an item", "emoji": true }, "options": [ { "text": { "type": "plain_text", "text": "Yes, we met up!", "emoji": true }, "value": "MetUp-Yes" }, { "text": { "type": "plain_text", "text": "No, we both cancelled.", "emoji": true }, "value": "MetUp-No-both" }, { "text": { "type": "plain_text", "text": "No, I cancelled.", "emoji": true }, "value": "MetUp-No-Me" }, { "text": { "type": "plain_text", "text": "No, they cancelled.", "emoji": true }, "value": "MetUp-No-Them" } ], "action_id": "static_select-action" }, "label": { "type": "plain_text", "text": "Did the meetup happen?", "emoji": true } }, { "type": "input", "block_id": "Rating", "element": { "type": "static_select", "placeholder": { "type": "plain_text", "text": "Select an item", "emoji": true }, "options": [ { "text": { "type": "plain_text", "text": "10", "emoji": true }, "value": "Rating-10" }, { "text": { "type": "plain_text", "text": "9", "emoji": true }, "value": "Rating-9" }, { "text": { "type": "plain_text", "text": "8", "emoji": true }, "value": "Rating-8" }, { "text": { "type": "plain_text", "text": "7", "emoji": true }, "value": "Rating-7" }, { "text": { "type": "plain_text", "text": "6", "emoji": true }, "value": "Rating-6" }, { "text": { "type": "plain_text", "text": "5", "emoji": true }, "value": "Rating-5" }, { "text": { "type": "plain_text", "text": "4", "emoji": true }, "value": "Rating-4" }, { "text": { "type": "plain_text", "text": "3", "emoji": true }, "value": "Rating-3" }, { "text": { "type": "plain_text", "text": "2", "emoji": true }, "value": "Rating-2" }, { "text": { "type": "plain_text", "text": "1", "emoji": true }, "value": "Rating-1" } ], "action_id": "static_select-action" }, "label": { "type": "plain_text", "text": "Overall, how was it 1 to 10?", "emoji": true } }, { "type": "input", "block_id": "Survey_Feedback", "element": { "type": "plain_text_input", "action_id": "plain_text_input-action" }, "label": { "type": "plain_text", "text": "[Optional] Anything else you want to share?", "emoji": true } }, { "type": "actions", "elements": [ { "type": "button", "text": { "type": "plain_text", "emoji": true, "text": "Submit Survey" }, "style": "primary", "value": "survey-complete" } ] } ] },

                'survey_completed':
                    { "blocks": [ { "type": "section", "text": { "type": "mrkdwn", "text": "Before the next Lunchtag pairings, please complete the survey below! We'll use it to try to improve your experience." } }, { "type": "section", "text": { "type": "mrkdwn", "text": ">:white_check_mark: *Your response has been recorded.* Thank you!" } } ] }
                    
                
                }
