AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LunchtagSlackBothandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 45
      Role: >-
        arn:aws:iam::895762781642:role/service-role/Lunchtag-Slack-Bot-handler-role-uyg7k9ls
      Environment:
        Variables:
          SLACK_BOT_TOKEN: xoxb-3977975994593-5046380600870-Jx7aTyMMP6WbYEVav8urvSNx
      Layers:
        - 'arn:aws:lambda:us-east-2:895762781642:layer:dependencies-layer:10'
        - 'arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python39:8'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
